spring.cloud.stream:
  function:
    definition: domainProcessor2
  bindings:
    domainProcessor2-in-0:
      destination: webdomains
    domainProcessor2-out-0:
      destination: activewebdomains
  kafka:
    bindings:
      domainProcessor2-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      domainProcessor2-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092
      consumer-properties:
        spring.json.trusted.packages: com.cloudofgoods.*


spring:
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"
    producer:
      properties:
        spring.json.add.type.headers: false
    streams:
      bootstrap-servers: "127.0.0.1:9092"
      application-id: spring-kafka-test
      properties:
        processing.guarantee: exactly_once
