spring:
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: com.cloudofgoods.cog.dataengineeringprocessing.model.*
    producer:
      properties:
        spring.json.add.type.headers: false
    streams:
      bootstrap-servers: 127.0.0.1:9092
      application-id: spring-kafka-test
      properties:
        processing.guarantee: exactly_once
